# DragonDiscordSync plugin by Fraithor! (Join my Public Server chromaMC.xyz) #
# Need help? go to https://discord.gg/5mVkqAyReB! #

Discord:
  Bot:
    Token: "TOKEN"
    Prefix: 'c!'
    Bot-activity: 'Playing'
    Bot-activity-text: 'minecraft with the boys'
    Bot-activity-url: 'https://www.twitch.tv/Fraithor' #Streaming only (optional)
  Channels:
    Main-Channel: ''
    ChatSync-ChannelID: ''
    AdvancementSync-ChannelID: ''
    DeathSync-ChannelID: ''
    JoinLeaveSync-ChannelID: ''
  Events:
    Options:
      PlayerHead: True
      PlayerHeadSize: 50
      ChatEmbedColor: '#ffffff'
      AchievementEmbedColor: '#00ff00'
      DeathEmbedColor: '#ff0000'
      JoinLeaveEmbedColor: '#ffb700'
    Log:
      Death: True
      Messages: True
      Achievements: True