# DragonDiscordSync plugin by Fraithor! (Website: Fraithor.com) #
# Need help? go to https://discord.gg/5mVkqAyReB! #

Discord:
  Bot:
    Token: TOKEN
    Prefix: c!
    Activity: Minecraft with the boys
    Status: Online
  Channels:
    Main-Channel: ''
    ChatSync-ChannelID: ''
    AdvancementSync-ChannelID: ''
    DeathSync-ChannelID: ''
    JoinLeaveSync-ChannelID: ''
  Events:
    Options:
      AchievementEmbedColor: '#00ff00'
      DeathEmbedColor: '#ff0000'
      JoinEmbedColor: '#ffb700'
      LeaveEmbedColor: '#ff0000'
    Sync:
      Death: True
      Messages: True
      Achievements: True
      JoinLeave: True
Minecraft:
  Options:
    ChatFormat: '&7&l[&b&lDiscord &f|&b %channel%&7] &b%user% &6&l» &f%message%'