#-----------------------
# ___  ___  ___
#|   \|   \/ __|
#| |) | |) \__ \
#|___/|___/|___/
# DragonDiscordSync
#-----------------------

Bot-token: ''
Bot-prefix: 'c!'

Main-ChannelID:
#Leave blank for same as Main-ChannelID:
ChatSync-ChannelID:
AdvancementSync-ChannelID:
DeathSync-ChannelID:


#Avaible activities: Playing, Listening, Watching, Streaming, Custom
Bot-activity: 'Playing'
Bot-activity-text: 'minecraft with the boys'
Bot-activity-url: 'https://www.twitch.tv/Fraithor' #Streaming only (optional)